### ISSUE TITLE
Shaman's Maelstrom Weapon not showing

### ISSUE THREAD

**Issue by Lyonshinigami** [ElvUI-WotLK/ElvUI_VisualProcs#2]
When using the plugin in my Shaman, the procs from my Maelstrom weapon talent doesn't show, even the menu is grayet out and I can't configure it.
The plugin works just fine with my Mage and DK, so I don't know what could be wrong.

**Comment by Pivaseq** [comment]
still Shaman's Maelstrom Weapon not glowing at 5 stacks
