### ISSUE TITLE
Surge of Light - Priest missing

### ISSUE THREAD

**Issue by Zidras** [ElvUI-WotLK/ElvUI_VisualProcs#4]
I noticed Priest aura Surge of Light [33151] was not activating. I edited the Data.lua file by just copy/pasting the Surge of Light on the Paladin section to the Priest section and it works. Sound appears doubled to me but I have no clue about LUA to figure it out.

[ElvUI_VisualProcs.zip](https://github.com/ElvUI-WotLK/ElvUI_VisualProcs/files/2949868/ElvUI_VisualProcs.zip)

**Comment by Zidras** [comment]
Anyone that wants to fix it:
line 760
`PRIEST = {
		-- Serendipity
		[63731] = 1,
		[63734] = 1,
		[63735] = 1,
                -- Surge of Light
		[33151] = 2,
	},`

line 844
`},
	PRIEST = {
		-- Serendipity
		{3, "Serendipity.blp", "Top", 1, 1, 1, 1},
                -- Surge of Light
		{0, "Surge_of_Light.blp", "Left + Right (Flipped)", 1, 1, 1, 1},
	},`

**Comment by Bunny67** [comment]
This added
I don't notice problems with sound

**Comment by Zidras** [comment]
Probably something double proccing that I didn't realize was happening. Anyway, it is officially fixed thank you 👍
