### ISSUE TITLE
More visual effects request.

### ISSUE THREAD

**Issue by mrnuggets** [ElvUI-WotLK/ElvUI_VisualProcs#5]
Hey.

I was wondering, if it's possible to add a glow for when you can use Hammer of Wrath, Execute and so on.

Would be neat.

Thanks.

**Comment by truekripp** [comment]
Get the addon "Cheese" for WotLK. Adds the special effect that came with Cataclysm. Works wonders, if you don't feel like sorting proc addons.

**Comment by mrnuggets** [comment]
> Get the addon "Cheese" for WotLK. Adds the special effect that came with Cataclysm. Works wonders, if you don't feel like sorting proc addons.

I've tried Cheese. Does not give a glow for Hammer of Wrath when available.

**Comment by mrnuggets** [comment]
Works.

https://gyazo.com/5e08d95802dc4598d401a8fef8ecc372

**Comment by Loaal** [comment]
#6 76671f570db969bc49f1c168c8cf16f388e86dd0
