### ISSUE TITLE
Молот гнева

### ISSUE THREAD

**Issue by weacomeout** [ElvUI-WotLK/ElvUI_VisualProcs#6]
После убийства первого моба за сеанс - всегда активирован.
![WoWScrnShot_111319_223613](https://user-images.githubusercontent.com/57728292/68798158-f2504880-0666-11ea-906c-800e1edfdbef.jpg)
Элв и его модули обновлены сегодня. Рекаунт и дбм.

**Comment by Bunny67** [comment]
Не получается воспроизвести

**Comment by weacomeout** [comment]
Обновился, почистил кэш. Скилл активирован всегда рандомным образом. Иногда подсветка гаснет. Какой-либо логики не обнаружил. 
В бою:
![WoWScrnShot_111419_192139](https://user-images.githubusercontent.com/57728292/68876484-942e6e80-0715-11ea-9093-508582063d06.jpg)
Вне боя:
![WoWScrnShot_111419_192147](https://user-images.githubusercontent.com/57728292/68876503-9db7d680-0715-11ea-9479-691464b7c9f9.jpg)
После использования скилла детектор все еще активен:
![WoWScrnShot_111419_192242](https://user-images.githubusercontent.com/57728292/68876569-bc1dd200-0715-11ea-9d9a-dbf27b0fda8c.jpg)

**Comment by Bunny67** [comment]
Обновлял ElvUI_VisualProcs? По коду без таргета не должно подсвечивать, обнови еще раз ElvUI_VisualProcs, чуть правок внес

**Comment by weacomeout** [comment]
Да, обновлял вижуалпрокс. Но вчера обновил вообще все.
Боюсь, исправления не внесли изменений.
Проследил одну закономерность, подсветка деактивируется, после смены таргета в бою. 
Вот убит пак мобов. Активен скилл:
![WoWScrnShot_111419_202522](https://user-images.githubusercontent.com/57728292/68881168-add3b400-071d-11ea-9da0-40552b9f5d35.jpg)
Вот я беру в таргет босса, и как только вешается бой, подсветка скилла пропадает:
![WoWScrnShot_111419_202531](https://user-images.githubusercontent.com/57728292/68881225-ccd24600-071d-11ea-8421-5f526cbb7838.jpg)

**Comment by Bunny67** [comment]
Получилось воспроизвести, и так же и пофиксить. Обнови еще раз

**Comment by weacomeout** [comment]
Отлично работает. Преогромнейшее спасибо тебе мужик, ты проделал титанический труд.
